[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 5

[[services]]
name = "api"
type = "web"
port = 3001
domains = ["jpr-moveis-rusticos-production.up.railway.app"]
